In [24]:
import numpy
import json
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from PIL import Image
import requests
from io import BytesIO
from skimage import feature
from skimage import exposure
import cv2
import json
import os

In [25]:
with open('train.json') as f:
    data = json.load(f)

In [26]:
price = data['price']
latitude = data['latitude']
longitude = data['longitude']
time = data['created']
pic = data['photos']

In [27]:
def u_to_image(url):
	response = requests.get(url)
	img = Image.open(BytesIO(response.content))
	# return the image
	return img

In [28]:
def image_to_hog(img):
    h = feature.hog(img,orientations=9,pixels_per_cell=(8,8),cells_per_block=(2,2),transform_sqrt=True,block_norm="L1")
    return h

In [29]:
len(pic)

49352

In [30]:
def resize(img):
    width, height = img.size  
    width, height = img.size  
    left = 4
    top = height / 5
    right = 154
    bottom = 3 * height / 5
    newsize = (round(width/4), round(height/4))
    im1 = img.crop((left, top, right, bottom))
    im1 = im1.resize(newsize)
    return im1

In [31]:
def append_record(record):
    f = open("my_file.txt", "a+")
    f.write(str(record))
    f.close()

In [32]:
# for x in pic:
#     image_feature = {}
#     tmp = []
#     for y in pic[x]:
#         try:
#             img = u_to_image(y)
#             tmp.append(image_to_hog(resize(img)))
#             del img
#         except (OSError,NameError):
#             print(y)
#     image_feature[int(x)]=tmp
#     append_record(image_feature)
# #     del tmp

In [33]:
for x in pic:
    image_feature = {}
    tmp = []
    for y in pic[x]:
        try:
            img = u_to_image(y)
            tmp.append(image_to_hog(resize(img)))
            del img
        except (OSError,NameError):
            print(y)
    image_feature[int(x)]=tmp
    y = np.load("save.npy",allow_pickle=True) if os.path.isfile("save.npy") else [] #get data if exist
    np.save("save.npy",np.append(y,image_feature))
    del tmp

KeyboardInterrupt: 

In [34]:
xl = np.load("save.npy",allow_pickle=True)
list(xl)

[{4: [array([0.03266927, 0.00774625, 0.0195234 , ..., 0.01239558, 0.00672868,
          0.03655479]),
   array([0.00537757, 0.00202607, 0.00096156, ..., 0.03992062, 0.01560334,
          0.041837  ]),
   array([0.01681791, 0.01954735, 0.0226479 , ..., 0.00833162, 0.00660109,
          0.00644425]),
   array([0.08432802, 0.01185744, 0.0006377 , ..., 0.00377436, 0.02272681,
          0.08384841]),
   array([0.00620986, 0.        , 0.        , ..., 0.        , 0.00615096,
          0.00547253]),
   array([0.00658667, 0.        , 0.00232874, ..., 0.01331056, 0.00724335,
          0.        ]),
   array([0.02379469, 0.00613916, 0.00613282, ..., 0.00066196, 0.00239219,
          0.24382377]),
   array([0.05641303, 0.03122497, 0.04573351, ..., 0.05154614, 0.00829885,
          0.        ]),
   array([0.01184979, 0.00993109, 0.03642224, ..., 0.00464863, 0.02245989,
          0.00542057]),
   array([0.08190639, 0.00988267, 0.03780298, ..., 0.01081893, 0.03970296,
          0.0443557 ]),
   arra